function initBatchImport(){
  const API='https://x58r-xped-p4y6.n7e.xano.io/api:0Ddhs4dT';
  const token=localStorage.getItem('ads_journey_token');
  const FILTER_KEY='ads_journey_franchise_filter';
  const trigger=document.getElementById('batchImportButton');
  if(!trigger)return;
  const host=document.createElement('div');
  host.innerHTML=`<div id="batchImportBackdrop" class="inquiry-modal-backdrop" hidden></div><section id="batchImportModal" class="inquiry-modal" hidden aria-modal="true" role="dialog"><div class="inquiry-modal-head"><div><p class="section-kicker">Backfill Tool</p><h2>Batch Import Inquiries</h2></div><button id="closeBatchImport" class="secondary-button" type="button">← Back</button></div><div class="inquiry-modal-form"><div class="inquiry-modal-grid"><label class="full"><span>Branch / location *</span><select id="batchFranchiseId"><option value="">Loading branches...</option></select></label><label class="full"><span>Inquiry records (JSON array) *</span><textarea id="batchImportData" rows="16" placeholder='[{"facebook_name":"Parent Name","facebook_profile_url":"https://facebook.com/username","first_message_at":"2026-10-03T10:30","inquiry_type":"rates","initial_note":"Asked about tuition."}]'></textarea></label></div><div id="batchImportError" class="inquiry-modal-error" hidden><span></span></div><div id="batchImportResults" class="journey-search-results" style="margin-top:10px"></div><div class="inquiry-modal-actions"><button id="clearBatchImport" class="secondary-button" type="button">Clear</button><button id="runBatchImport" class="journey-primary" type="button">Import Batch</button></div></div></section>`;
  document.body.appendChild(host);
  const modal=document.getElementById('batchImportModal'),backdrop=document.getElementById('batchImportBackdrop'),franchise=document.getElementById('batchFranchiseId'),textarea=document.getElementById('batchImportData'),errorBox=document.getElementById('batchImportError'),errorText=errorBox.querySelector('span'),results=document.getElementById('batchImportResults'),runButton=document.getElementById('runBatchImport');
  trigger.addEventListener('click',openModal);document.getElementById('closeBatchImport').addEventListener('click',closeModal);backdrop.addEventListener('click',closeModal);document.getElementById('clearBatchImport').addEventListener('click',()=>{textarea.value='';results.innerHTML='';hideError();});
  runButton.addEventListener('click',runImport);document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!modal.hidden)closeModal();});
  async function openModal(){hideError();results.innerHTML='';modal.hidden=false;backdrop.hidden=false;document.body.classList.add('modal-open');await loadFranchises();textarea.focus();}
  function closeModal(){modal.hidden=true;backdrop.hidden=true;document.body.classList.remove('modal-open');}
  async function loadFranchises(){franchise.disabled=true;franchise.innerHTML='<option value="">Loading branches...</option>';try{const response=await fetch(`${API}/ad_franchises`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('Unable to load franchise locations.');const data=await response.json();const rows=Array.isArray(data)?data:(data.items||data.records||data.franchise||data.franchises||[]);franchise.innerHTML='<option value="">Select branch</option>';rows.forEach(row=>{const option=document.createElement('option');option.value=row.id;option.textContent=row.location||row.name||row.franchise_name||row.branch_name||`Branch ${row.id}`;franchise.appendChild(option);});const saved=JSON.parse(localStorage.getItem(FILTER_KEY)||'null');if(Array.isArray(saved)&&saved.length===1&&rows.some(row=>Number(row.id)===Number(saved[0])))franchise.value=String(saved[0]);franchise.disabled=false;}catch(error){franchise.innerHTML='<option value="">Unable to load branches</option>';showError(error.message);}}
  function parseRecords(){let records;try{records=JSON.parse(textarea.value.trim());}catch(error){throw new Error('The batch is not valid JSON.');}if(!Array.isArray(records)||!records.length)throw new Error('Paste a JSON array with at least one inquiry.');return records.map((record,index)=>normalizeRecord(record,index));}
  function normalizeRecord(record,index){if(!record||typeof record!=='object')throw new Error(`Record ${index+1} is not an object.`);const name=String(record.facebook_name||'').trim(),profile=String(record.facebook_profile_url||'').trim();if(!name)throw new Error(`Record ${index+1} is missing facebook_name.`);if(!profile)throw new Error(`Record ${index+1} is missing facebook_profile_url.`);const normalizedProfile=/^https?:\/\//i.test(profile)?profile:`https://${profile}`;const timestamp=toTimestamp(record.first_message_at);if(!timestamp)throw new Error(`Record ${index+1} (${name}) has an invalid first_message_at.`);return{facebook_name:name,facebook_profile_url:normalizedProfile,facebook_username:String(record.facebook_username||usernameFromProfile(normalizedProfile)||'').trim()||null,ad_id:record.ad_id?String(record.ad_id).trim():null,first_message_at:timestamp,inquiry_type:record.inquiry_type||null,initial_note:record.initial_note?String(record.initial_note).trim():null};}
  function toTimestamp(value){if(typeof value==='number'&&Number.isFinite(value))return value;const raw=String(value||'').trim();if(!raw)return 0;const date=new Date(raw);return Number.isNaN(date.getTime())?0:date.getTime();}
  function usernameFromProfile(url){try{const path=new URL(url).pathname.replace(/^\/+|\/+$/g,'');return path&&!path.includes('/')?path:'';}catch(error){return'';}}
  async function runImport(){hideError();results.innerHTML='';if(!franchise.value){showError('Select the branch for this batch.');return;}let records;try{records=parseRecords();}catch(error){showError(error.message);return;}runButton.disabled=true;runButton.textContent=`Importing 0 / ${records.length}`;const franchiseId=Number(franchise.value);let created=0,duplicates=0,failed=0,lastData=null;const rows=[];for(let i=0;i<records.length;i++){const record=records[i];runButton.textContent=`Importing ${i+1} / ${records.length}`;const payload={...record,franchise_id:franchiseId,status:'new',is_active:true,parent_id:null,student_id:null};try{const response=await fetch(`${API}/ad_inquiry_create`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(response.ok){created++;lastData=data;rows.push({name:record.facebook_name,status:'Created'});continue;}const message=String(data.message||data.error||data.detail||`HTTP ${response.status}`);if(/already has an inquiry record|already exists/i.test(message)){duplicates++;rows.push({name:record.facebook_name,status:'Duplicate — skipped'});}else{failed++;rows.push({name:record.facebook_name,status:`Failed — ${message}`});}}catch(error){failed++;rows.push({name:record.facebook_name,status:`Failed — ${error.message||'Network error'}`});}}
    results.innerHTML=`<div class="search-empty" style="text-align:left"><strong>Batch complete:</strong> ${created} created · ${duplicates} duplicates · ${failed} failed</div>`+rows.map(row=>`<div class="search-result-row"><strong>${escapeHtml(row.name)}</strong><span>${escapeHtml(row.status)}</span></div>`).join('');if(created&&lastData)window.dispatchEvent(new CustomEvent('inquiry-created',{detail:lastData}));runButton.disabled=false;runButton.textContent='Import Batch';}
  function showError(message){errorText.textContent=message;errorBox.hidden=false;}
  function hideError(){errorText.textContent='';errorBox.hidden=true;}
  function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initBatchImport);else initBatchImport();