const API_BASE_URL='https://x58r-xped-p4y6.n7e.xano.io/api:0Ddhs4dT';
const ME_ENDPOINT='/ad_journey_me';
const FRANCHISE_ENDPOINT='/ad_franchises';
const TOKEN_KEY='ads_journey_token';
const USER_KEY='ads_journey_user';
const FILTER_KEY='ads_journey_franchise_filter';
const token=localStorage.getItem(TOKEN_KEY);
if(!token)window.location.replace('index.html');
const userName=document.getElementById('userName');
const logoutButton=document.getElementById('logoutButton');
const franchiseFilterButton=document.getElementById('franchiseFilterButton');
const franchiseFilterPanel=document.getElementById('franchiseFilterPanel');
const closeFranchiseFilter=document.getElementById('closeFranchiseFilter');
const backFranchiseFilter=document.getElementById('backFranchiseFilter');
const franchiseSearch=document.getElementById('franchiseSearch');
const franchiseCheckboxList=document.getElementById('franchiseCheckboxList');
const selectAllFranchises=document.getElementById('selectAllFranchises');
const clearAllFranchises=document.getElementById('clearAllFranchises');
const dashboardModalBackdrop=document.getElementById('dashboardModalBackdrop');
const journeySearchInput=document.getElementById('journeySearchInput');
const journeySearchResults=document.getElementById('journeySearchResults');
let franchises=[];
let selectedFranchiseIds=new Set();
start();
async function start(){await validateLogin();await loadFranchises();setupDashboardModals();setupJourneySearch();}
async function validateLogin(){try{const response=await fetch(`${API_BASE_URL}${ME_ENDPOINT}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('AUTH_FAILED');const data=await response.json();const user=data.ad_user||data.user||data;localStorage.setItem(USER_KEY,JSON.stringify(user));userName.textContent=user.name||user.email||'Admin';}catch(error){logout();}}
async function loadFranchises(){try{const response=await fetch(`${API_BASE_URL}${FRANCHISE_ENDPOINT}`,{headers:{Authorization:`Bearer ${token}`}});if(response.status===401){logout();return}if(!response.ok)throw new Error('Unable to load franchises.');const data=await response.json();franchises=Array.isArray(data)?data:(data.items||data.records||data.franchise||data.franchises||[]);restoreSelection();renderFranchiseList();updateFilterLabel();applyFranchiseFilter();}catch(error){franchiseCheckboxList.innerHTML='<p class="filter-error">Unable to load franchise locations.</p>';}}
function restoreSelection(){const saved=JSON.parse(localStorage.getItem(FILTER_KEY)||'null');if(Array.isArray(saved)&&saved.length)selectedFranchiseIds=new Set(saved.map(Number));else selectedFranchiseIds=new Set(franchises.map(item=>Number(item.id)));}
function renderFranchiseList(search=''){const query=search.trim().toLowerCase();franchiseCheckboxList.innerHTML='';franchises.filter(item=>franchiseName(item).toLowerCase().includes(query)).forEach(item=>{const id=Number(item.id);const label=document.createElement('label');label.className='checkbox-item';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=selectedFranchiseIds.has(id);checkbox.addEventListener('change',()=>{if(checkbox.checked)selectedFranchiseIds.add(id);else selectedFranchiseIds.delete(id);saveSelection();updateFilterLabel();applyFranchiseFilter();});const span=document.createElement('span');span.textContent=franchiseName(item);label.append(checkbox,span);franchiseCheckboxList.appendChild(label);});}
function franchiseName(item){return item.location||item.name||item.franchise_name||item.branch_name||`Branch ${item.id}`;}
function selectedFranchiseNames(){return new Set(franchises.filter(item=>selectedFranchiseIds.has(Number(item.id))).map(franchiseName));}
function saveSelection(){localStorage.setItem(FILTER_KEY,JSON.stringify([...selectedFranchiseIds]));}
function updateFilterLabel(){const total=franchises.length;const selected=selectedFranchiseIds.size;let text='Franchises: ';if(!total)text+='No Locations';else if(selected===total)text+=`All ${total}`;else if(selected===0)text+='None';else text+=`${selected} selected`;franchiseFilterButton.firstChild.textContent=`${text} `;}
function applyFranchiseFilter(){const names=selectedFranchiseNames();document.querySelectorAll('.journey-card[data-franchise]').forEach(card=>{card.hidden=!names.has(card.dataset.franchise);});document.querySelectorAll('.journey-column').forEach(column=>{const visible=[...column.querySelectorAll('.journey-card')].filter(card=>!card.hidden).length;column.querySelector('.column-count').textContent=visible;});updateSummaryCounts();filterPopupRows(names);}
function updateSummaryCounts(){const visible=[...document.querySelectorAll('.journey-card')].filter(card=>!card.hidden);const needsAttention=visible.filter(card=>card.classList.contains('urgent')).length;const waitingFranchise=visible.filter(card=>card.closest('[data-stage="awaiting-outcome"]')).length;const waitingParent=visible.filter(card=>card.dataset.waitingParent==='true').length;const enrollment=visible.filter(card=>card.closest('[data-stage="enrollment"]')).length;const summary=document.querySelectorAll('.summary-value');if(summary[0])summary[0].textContent=visible.length;if(summary[1])summary[1].textContent=needsAttention;if(summary[2])summary[2].textContent=waitingFranchise;if(summary[3])summary[3].textContent=waitingParent;if(summary[4])summary[4].textContent=enrollment;}
function filterPopupRows(names){document.querySelectorAll('#adminActivityModal .activity-row').forEach(row=>{const location=row.querySelector('strong')?.textContent.trim();row.hidden=location?!names.has(location):false;});document.querySelectorAll('#locationPerformanceModal tbody tr').forEach(row=>{const location=row.cells[0]?.textContent.trim();row.hidden=location?!names.has(location):false;});}
function openFilter(){franchiseFilterPanel.hidden=false;franchiseSearch.focus();}
function closeFilter(){franchiseFilterPanel.hidden=true;franchiseSearch.value='';renderFranchiseList();}
franchiseFilterButton.addEventListener('click',()=>franchiseFilterPanel.hidden?openFilter():closeFilter());
closeFranchiseFilter.addEventListener('click',closeFilter);
backFranchiseFilter.addEventListener('click',closeFilter);
franchiseSearch.addEventListener('input',()=>renderFranchiseList(franchiseSearch.value));
selectAllFranchises.addEventListener('click',()=>{selectedFranchiseIds=new Set(franchises.map(item=>Number(item.id)));saveSelection();renderFranchiseList(franchiseSearch.value);updateFilterLabel();applyFranchiseFilter();});
clearAllFranchises.addEventListener('click',()=>{selectedFranchiseIds.clear();saveSelection();renderFranchiseList(franchiseSearch.value);updateFilterLabel();applyFranchiseFilter();});
document.addEventListener('click',event=>{if(!franchiseFilterPanel.hidden&&!event.target.closest('.filter-wrap'))closeFilter();});
function setupDashboardModals(){const map={journeySearchButton:'journeySearchModal',adminActivityButton:'adminActivityModal',locationPerformanceButton:'locationPerformanceModal',marketingPerformanceButton:'marketingPerformanceModal'};Object.entries(map).forEach(([buttonId,modalId])=>document.getElementById(buttonId)?.addEventListener('click',()=>openDashboardModal(modalId)));document.querySelectorAll('.modal-close').forEach(button=>button.addEventListener('click',closeDashboardModals));dashboardModalBackdrop.addEventListener('click',closeDashboardModals);document.addEventListener('keydown',event=>{if(event.key==='Escape')closeDashboardModals();});}
function openDashboardModal(id){closeFilter();document.querySelectorAll('.dashboard-modal').forEach(modal=>modal.hidden=true);const modal=document.getElementById(id);if(!modal)return;modal.hidden=false;dashboardModalBackdrop.hidden=false;if(id==='journeySearchModal'){journeySearchInput.value='';filterJourneySearch();setTimeout(()=>journeySearchInput.focus(),0);}}
function closeDashboardModals(){document.querySelectorAll('.dashboard-modal').forEach(modal=>modal.hidden=true);dashboardModalBackdrop.hidden=true;}
function setupJourneySearch(){document.getElementById('runJourneySearch')?.addEventListener('click',filterJourneySearch);journeySearchInput?.addEventListener('input',filterJourneySearch);journeySearchInput?.addEventListener('keydown',event=>{if(event.key==='Enter')filterJourneySearch();});document.querySelectorAll('.reactivate-journey').forEach(button=>button.addEventListener('click',reactivateSearchRecord));document.querySelectorAll('.open-search-result').forEach(button=>button.addEventListener('click',openSearchRecord));}
function filterJourneySearch(){if(!journeySearchResults)return;const query=(journeySearchInput?.value||'').trim().toLowerCase();let shown=0;journeySearchResults.querySelectorAll('.search-result-card').forEach(card=>{const match=!query||card.dataset.search.includes(query);card.hidden=!match;if(match)shown++;});let empty=journeySearchResults.querySelector('.search-empty');if(!shown){if(!empty){empty=document.createElement('div');empty.className='search-empty';empty.textContent='No matching journeys found.';journeySearchResults.appendChild(empty);}empty.hidden=false;}else if(empty)empty.hidden=true;}
function reactivateSearchRecord(event){const card=event.currentTarget.closest('.search-result-card');if(!card)return;card.classList.remove('dormant');card.querySelector('.record-state').className='record-state active-state';card.querySelector('.record-state').textContent='Active · Inquiry';event.currentTarget.remove();const name=card.querySelector('strong').textContent.trim();const location=card.querySelector('.search-result-head div span').textContent.split('·')[0].trim();const inquiryColumn=document.querySelector('[data-stage="inquiry"] .journey-column-list');if(inquiryColumn&&!document.querySelector(`.journey-card[data-reactivated="${name}"]`)){const row=document.createElement('article');row.className='journey-card work-row';row.dataset.franchise=location;row.dataset.status='active';row.dataset.reactivated=name;row.innerHTML=`<div class="card-top"><strong>${name}</strong><span class="priority quiet">Reactivated</span></div><p>${location} · Returned to conversation</p><div class="card-next"><span>Continue conversation</span><time>Now</time></div>`;inquiryColumn.prepend(row);window.dispatchEvent(new CustomEvent('journey-card-added',{detail:{row}}));applyFranchiseFilter();}}
function openSearchRecord(event){const result=event.currentTarget.closest('.search-result-card');const name=result?.querySelector('strong')?.textContent.trim();if(!name)return;const boardCard=[...document.querySelectorAll('.journey-card')].find(card=>card.querySelector('.card-top strong')?.textContent.trim()===name);if(boardCard){closeDashboardModals();boardCard.click();return;}const state=result.querySelector('.record-state')?.textContent||'Record';result.querySelector('p').textContent=`${state}. Reactivate this journey to return it to the working board.`;}
logoutButton.addEventListener('click',logout);
function logout(){localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(USER_KEY);window.location.replace('index.html');}
const journeyStyle=document.createElement('link');journeyStyle.rel='stylesheet';journeyStyle.href='journey_panel.css';document.head.appendChild(journeyStyle);
const journeyScript=document.createElement('script');journeyScript.src='journey_panel.js';document.body.appendChild(journeyScript);
const inquiryStyle=document.createElement('link');inquiryStyle.rel='stylesheet';inquiryStyle.href='inquiry_modal.css';document.head.appendChild(inquiryStyle);
const inquiryScript=document.createElement('script');inquiryScript.src='inquiry_modal.js';document.body.appendChild(inquiryScript);