const API_BASE_URL='https://x58r-xped-p4y6.n7e.xano.io/api:0Ddhs4dT';
const ME_ENDPOINT='/ad_journey_me';
const FRANCHISE_ENDPOINT='/ad_franchises';
const BOARD_ENDPOINT='/ad_journey_board';
const ADMIN_ACTIVITY_ENDPOINT='/ad_admin_activity';
const TOKEN_KEY='ads_journey_token';
const USER_KEY='ads_journey_user';
const FILTER_KEY='ads_journey_franchise_filter';
const token=localStorage.getItem(TOKEN_KEY);
if(!token)window.location.replace('index.html');
const userName=document.getElementById('userName');
const logoutButton=document.getElementById('logoutButton');
const franchiseFilterButton=document.getElementById('franchiseFilterButton');
const franchiseFilterPanel=document.getElementById('franchiseFilterPanel');
const closeFranchiseFilter=document.getElementById('closeFranchiseFilter');
const backFranchiseFilter=document.getElementById('backFranchiseFilter');
const franchiseCheckboxList=document.getElementById('franchiseCheckboxList');
const selectAllFranchises=document.getElementById('selectAllFranchises');
const clearAllFranchises=document.getElementById('clearAllFranchises');
const dashboardModalBackdrop=document.getElementById('dashboardModalBackdrop');
const journeySearchInput=document.getElementById('journeySearchInput');
const journeySearchResults=document.getElementById('journeySearchResults');
let franchises=[];
let selectedFranchiseIds=new Set();
let boardJourneys=[];
start();
window.addEventListener('inquiry-created',event=>{const data=event.detail||{};const inquiry=data.ad_inquiry||data.inquiry||data;const journey=data.ad_journey||data.journey||{};usageEvent('inquiry_created',{module:'new_inquiry',action:'create',target:'inquiry',inquiry_id:Number(inquiry.id)||0,journey_id:Number(journey.id)||0,franchise_id:Number(inquiry.franchise_id||journey.franchise_id)||0,inquiry_type:inquiry.inquiry_type||null});loadBoard();});
async function start(){await validateLogin();await loadFranchises();setupDashboardModals();setupJourneySearch();}
async function validateLogin(){try{const response=await fetch(`${API_BASE_URL}${ME_ENDPOINT}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('AUTH_FAILED');const data=await response.json();const user=data.ad_user||data.user||data;localStorage.setItem(USER_KEY,JSON.stringify(user));userName.textContent=user.name||user.email||'Admin';}catch(error){logout();}}
async function loadFranchises(){try{const response=await fetch(`${API_BASE_URL}${FRANCHISE_ENDPOINT}`,{headers:{Authorization:`Bearer ${token}`}});if(response.status===401){logout();return}if(!response.ok)throw new Error('Unable to load franchises.');const data=await response.json();franchises=Array.isArray(data)?data:(data.items||data.records||data.franchise||data.franchises||[]);restoreSelection();renderFranchiseList();updateFilterLabel();syncUsageFranchiseSelection('initial_load');await loadBoard();}catch(error){franchiseCheckboxList.innerHTML='<p class="filter-error">Unable to load franchise locations.</p>';}}
function restoreSelection(){const saved=JSON.parse(localStorage.getItem(FILTER_KEY)||'null');if(Array.isArray(saved)&&saved.length)selectedFranchiseIds=new Set(saved.map(Number));else selectedFranchiseIds=new Set(franchises.map(item=>Number(item.id)));}
function renderFranchiseList(){franchiseCheckboxList.innerHTML='';franchises.forEach(item=>{const id=Number(item.id);const label=document.createElement('label');label.className=`checkbox-item franchise-select-option${selectedFranchiseIds.has(id)?' selected':''}`;label.dataset.franchiseId=String(id);label.style.setProperty('--franchise-accent',franchiseAccent(id));const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=selectedFranchiseIds.has(id);checkbox.addEventListener('change',async()=>{if(checkbox.checked)selectedFranchiseIds.add(id);else selectedFranchiseIds.delete(id);label.classList.toggle('selected',checkbox.checked);saveSelection();updateFilterLabel();syncUsageFranchiseSelection('checkbox',id,checkbox.checked);await loadBoard();});const span=document.createElement('span');span.textContent=franchiseName(item);label.append(checkbox,span);franchiseCheckboxList.appendChild(label);});}
function franchiseAccent(id){return`hsl(${(Number(id)*47)%360} 30% 58%)`;}
function franchiseName(item){return item.location||item.name||item.franchise_name||item.branch_name||`Branch ${item.id}`;}
function saveSelection(){localStorage.setItem(FILTER_KEY,JSON.stringify([...selectedFranchiseIds]));}
function updateFilterLabel(){const total=franchises.length;const selected=selectedFranchiseIds.size;let text='Franchises: ';if(!total)text+='No Locations';else if(selected===total)text+=`All ${total}`;else if(selected===0)text+='None';else text+=`${selected} selected`;franchiseFilterButton.firstChild.textContent=`${text} `;}
async function loadBoard(){clearBoard();if(!selectedFranchiseIds.size){boardJourneys=[];updateSummaryCounts();return}try{const params=new URLSearchParams();[...selectedFranchiseIds].forEach(id=>params.append('franchise_ids[]',String(id)));const response=await fetch(`${API_BASE_URL}${BOARD_ENDPOINT}?${params.toString()}`,{headers:{Authorization:`Bearer ${token}`}});if(response.status===401){logout();return}if(!response.ok)throw new Error('BOARD_LOAD_FAILED');const data=await response.json();boardJourneys=Array.isArray(data.journeys)?data.journeys:[];renderBoard(boardJourneys);filterPopupRows(new Set(boardJourneys.map(journey=>journeyLocation(journey))));}catch(error){showBoardError();}}
function clearBoard(){document.querySelectorAll('.journey-column-list').forEach(list=>list.innerHTML='');document.querySelectorAll('.journey-column .column-count').forEach(count=>count.textContent='0');}
function renderBoard(journeys){clearBoard();journeys.forEach(journey=>{const stage=normalizeStage(journey.current_stage);const list=document.querySelector(`[data-stage="${stage}"] .journey-column-list`);if(!list)return;const row=buildJourneyCard(journey);list.appendChild(row);window.dispatchEvent(new CustomEvent('journey-card-added',{detail:{row,journey}}));});document.querySelectorAll('.journey-column').forEach(column=>{column.querySelector('.column-count').textContent=column.querySelectorAll('.journey-card').length;});updateSummaryCounts();}
function buildJourneyCard(journey){const inquiry=journey._ad_inquiry||{};const location=journeyLocation(journey);const stage=normalizeStage(journey.current_stage);const status=String(journey.current_status||'active');const nextAt=Number(journey.next_action_at)||0;const urgent=nextAt>0&&nextAt<=Date.now();const waitingParent=isWaitingParent(journey);const article=document.createElement('article');article.className=`journey-card work-row${urgent?' urgent':''}`;article.dataset.franchise=location;article.dataset.status=status;article.dataset.journeyId=String(journey.id);article.dataset.inquiryId=String(journey.ad_inquiry_id||'');if(waitingParent)article.dataset.waitingParent='true';const badgeClass=urgent?'overdue':badgeClassFor(stage,status,waitingParent);const badgeText=urgent?'Due now':badgeTextFor(stage,status,waitingParent);if(stage==='inquiry'){article.innerHTML=`<div class="card-top"><strong>${escapeHtml(inquiry.facebook_name||`Journey #${journey.id}`)}</strong><time>${escapeHtml(formatInquiryDateTime(inquiry.first_message_at||inquiry.created_at))}</time></div><p>${escapeHtml(cardDescription(journey,inquiry,location))}</p>`;}else{article.innerHTML=`<div class="card-top"><strong>${escapeHtml(inquiry.facebook_name||`Journey #${journey.id}`)}</strong><span class="priority ${badgeClass}">${escapeHtml(badgeText)}</span></div><p>${escapeHtml(cardDescription(journey,inquiry,location))}</p><div class="card-next"><span>${escapeHtml(nextActionText(journey,stage))}</span><time>${escapeHtml(nextTimeText(journey))}</time></div>`;}return article;}
function normalizeStage(stage){const value=String(stage||'inquiry').toLowerCase();if(value==='awaiting_outcome')return'awaiting-outcome';if(value==='follow_up')return'followup';return value;}
function journeyLocation(journey){const franchise=journey._franchise||{};return franchise.location||franchise.name||franchise.branch_name||franchiseName(franchises.find(item=>Number(item.id)===Number(journey.franchise_id))||{id:journey.franchise_id});}
function cardDescription(journey,inquiry,location){const stage=normalizeStage(journey.current_stage);if(stage==='inquiry'){const detail=inquiry.inquiry_type?titleCase(inquiry.inquiry_type):'Inquiry';return`${location} · ${detail}`;}if(stage==='scheduled')return`${location} · ${titleCase(journey.current_status||'Scheduled')}`;if(stage==='awaiting-outcome')return`${location} · Visit / trial completed`;if(stage==='followup')return`${location} · ${isWaitingParent(journey)?'Parent deciding':'Follow-up'}`;if(stage==='enrollment')return`${location} · Enrollment reported`;return location;}
function formatInquiryDateTime(value){const timestamp=Number(value)||0;if(!timestamp)return'—';const date=new Date(timestamp);return`${date.toLocaleDateString([],{month:'short',day:'numeric'})} · ${date.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`;}
function nextActionText(journey,stage){const type=String(journey.next_action_type||'none');if(type&&type!=='none')return titleCase(type);if(stage==='inquiry')return'Continue conversation';if(stage==='scheduled')return'Wait for scheduled visit / trial';if(stage==='awaiting-outcome')return'Get result from franchise';if(stage==='followup')return isWaitingParent(journey)?'Waiting on parent':'Follow up with parent';if(stage==='enrollment')return'Process enrollment';return'No next action';}
function nextTimeText(journey){const value=Number(journey.next_action_at)||0;if(!value)return'—';const date=new Date(value);const now=new Date();if(date.toDateString()===now.toDateString())return date.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});return date.toLocaleDateString([], {month:'short',day:'numeric'});}
function isWaitingParent(journey){const status=String(journey.current_status||'').toLowerCase();const action=String(journey.next_action_type||'').toLowerCase();return status.includes('parent')||status.includes('decid')||status.includes('thinking')||action==='wait_parent'||action==='waiting_parent';}
function badgeClassFor(stage,status,waitingParent){if(waitingParent)return'waiting-parent';if(stage==='awaiting-outcome')return'waiting';if(stage==='scheduled')return'upcoming';if(stage==='enrollment')return'upcoming';if(status==='new')return'quiet';return'quiet';}
function badgeTextFor(stage,status,waitingParent){if(waitingParent)return'Waiting on Parent';if(stage==='awaiting-outcome')return'Waiting';if(stage==='scheduled')return'Scheduled';if(stage==='enrollment')return'Reported';return titleCase(status||'Active');}
function updateSummaryCounts(){const visible=boardJourneys;const needsAttention=visible.filter(journey=>{const due=Number(journey.next_action_at)||0;return due>0&&due<=Date.now();}).length;const waitingFranchise=visible.filter(journey=>normalizeStage(journey.current_stage)==='awaiting-outcome').length;const waitingParent=visible.filter(isWaitingParent).length;const enrollment=visible.filter(journey=>normalizeStage(journey.current_stage)==='enrollment').length;const summary=document.querySelectorAll('.summary-value');if(summary[0])summary[0].textContent=visible.length;if(summary[1])summary[1].textContent=needsAttention;if(summary[2])summary[2].textContent=waitingFranchise;if(summary[3])summary[3].textContent=waitingParent;if(summary[4])summary[4].textContent=enrollment;}
function showBoardError(){clearBoard();const first=document.querySelector('[data-stage="inquiry"] .journey-column-list');if(first)first.innerHTML='<div class="filter-error">Unable to load journey board.</div>';boardJourneys=[];updateSummaryCounts();}
function filterPopupRows(names){document.querySelectorAll('#adminActivityModal .activity-row').forEach(row=>{const location=row.querySelector('strong')?.textContent.trim();row.hidden=location?!names.has(location):false;});document.querySelectorAll('#locationPerformanceModal tbody tr').forEach(row=>{const location=row.cells[0]?.textContent.trim();row.hidden=location?!names.has(location):false;});}
function openFilter(){franchiseFilterPanel.hidden=false;}
function closeFilter(){franchiseFilterPanel.hidden=true;}
franchiseFilterButton.addEventListener('click',()=>franchiseFilterPanel.hidden?openFilter():closeFilter());
closeFranchiseFilter?.addEventListener('click',closeFilter);
backFranchiseFilter.addEventListener('click',closeFilter);
selectAllFranchises.addEventListener('click',async()=>{selectedFranchiseIds=new Set(franchises.map(item=>Number(item.id)));saveSelection();renderFranchiseList();updateFilterLabel();syncUsageFranchiseSelection('select_all');await loadBoard();});
clearAllFranchises.addEventListener('click',async()=>{selectedFranchiseIds.clear();saveSelection();renderFranchiseList();updateFilterLabel();syncUsageFranchiseSelection('clear_all');await loadBoard();});
document.addEventListener('click',event=>{if(!franchiseFilterPanel.hidden&&!event.target.closest('.filter-wrap'))closeFilter();});
function setupDashboardModals(){const map={journeySearchButton:'journeySearchModal',adminActivityButton:'adminActivityModal',locationPerformanceButton:'locationPerformanceModal',marketingPerformanceButton:'marketingPerformanceModal'};Object.entries(map).forEach(([buttonId,modalId])=>document.getElementById(buttonId)?.addEventListener('click',()=>openDashboardModal(modalId)));document.querySelectorAll('.modal-close').forEach(button=>button.addEventListener('click',closeDashboardModals));dashboardModalBackdrop.addEventListener('click',closeDashboardModals);document.addEventListener('keydown',event=>{if(event.key==='Escape')closeDashboardModals();});}
function openDashboardModal(id){closeFilter();document.querySelectorAll('.dashboard-modal').forEach(modal=>modal.hidden=true);const modal=document.getElementById(id);if(!modal)return;modal.hidden=false;dashboardModalBackdrop.hidden=false;if(id==='journeySearchModal'){journeySearchInput.value='';filterJourneySearch();setTimeout(()=>journeySearchInput.focus(),0);}if(id==='adminActivityModal'){usageEvent('admin_activity_opened',{module:'admin_activity',action:'open',selected_franchise_count:selectedFranchiseIds.size});loadAdminActivity();}if(id==='locationPerformanceModal')usageEvent('location_performance_opened',{module:'location_performance',action:'open',selected_franchise_count:selectedFranchiseIds.size});if(id==='marketingPerformanceModal')usageEvent('marketing_performance_opened',{module:'marketing_performance',action:'open',selected_franchise_count:selectedFranchiseIds.size});}
function closeDashboardModals(){document.querySelectorAll('.dashboard-modal').forEach(modal=>modal.hidden=true);dashboardModalBackdrop.hidden=true;}
async function loadAdminActivity(){const list=document.querySelector('#adminActivityModal .activity-list');if(!list)return;if(!selectedFranchiseIds.size){list.innerHTML='<div class="search-empty">No franchise locations selected.</div>';return;}list.innerHTML='<div class="search-empty">Loading activity...</div>';try{const params=new URLSearchParams();[...selectedFranchiseIds].forEach(id=>params.append('franchise_ids[]',String(id)));const response=await fetch(`${API_BASE_URL}${ADMIN_ACTIVITY_ENDPOINT}?${params.toString()}`,{headers:{Authorization:`Bearer ${token}`}});if(response.status===401){logout();return}if(!response.ok)throw new Error('ACTIVITY_LOAD_FAILED');const data=await response.json();const events=Array.isArray(data.ad_journey_events)?data.ad_journey_events:[];renderAdminActivity(events);}catch(error){list.innerHTML='<div class="search-empty">Unable to load admin activity.</div>';}}
function renderAdminActivity(events){const list=document.querySelector('#adminActivityModal .activity-list');if(!list)return;list.innerHTML='';if(!events.length){list.innerHTML='<div class="search-empty">No admin activity found for the selected locations.</div>';return;}events.forEach(event=>{const admin=event._ad_user?.name||'Admin';const journey=event._ad_journey||{};const inquiry=journey._ad_inquiry||{};const franchise=journey.__franchise||{};const parent=inquiry.facebook_name||`Journey #${event.ad_journey_id||journey.id||''}`;const location=franchise.name||franchise.branch_name||franchiseName(franchises.find(item=>Number(item.id)===Number(event.franchise_id))||{id:event.franchise_id});const row=document.createElement('div');row.className='activity-row';row.innerHTML=`<time>${escapeHtml(formatActivityTime(event.event_at||event.created_at))}</time><span><b>${escapeHtml(admin)}</b> · ${escapeHtml(activityDescription(event,parent))}</span><strong>${escapeHtml(location)}</strong>`;list.appendChild(row);});}
function activityDescription(event,parent){const map={inquiry_created:`Created inquiry for ${parent}`,question_received:`Recorded question for ${parent}`,visit_scheduled:`Scheduled visit for ${parent}`,trial_scheduled:`Scheduled free trial for ${parent}`,franchise_notified:`Sent ${parent} to franchise`,franchise_update_due:`Franchise update due for ${parent}`,franchise_result_received:`Recorded franchise result for ${parent}`,visit_completed:`Recorded visit completed for ${parent}`,trial_completed:`Recorded trial completed for ${parent}`,no_show:`Marked ${parent} as no-show`,rescheduled:`Rescheduled ${parent}`,cancelled:`Cancelled appointment for ${parent}`,follow_up_scheduled:`Scheduled follow-up for ${parent}`,follow_up_completed:`Completed follow-up for ${parent}`,parent_interested:`Marked ${parent} interested`,parent_not_interested:`Marked ${parent} not interested`,enrollment_reported:`Reported enrollment for ${parent}`,enrollment_processed:`Processed enrollment for ${parent}`,journey_closed:`Closed journey for ${parent}`,journey_dormant:`Marked ${parent} dormant`,journey_reactivated:`Reactivated ${parent}`};return map[event.event_type]||`${titleCase(event.event_type||'Activity')} · ${parent}`;}
function formatActivityTime(value){const timestamp=Number(value)||0;if(!timestamp)return'—';const date=new Date(timestamp);const now=new Date();const time=date.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});if(date.toDateString()===now.toDateString())return time;return`${date.toLocaleDateString([],{month:'short',day:'numeric'})} ${time}`;}
function setupJourneySearch(){document.getElementById('runJourneySearch')?.addEventListener('click',()=>runJourneySearch('button'));journeySearchInput?.addEventListener('input',filterJourneySearch);journeySearchInput?.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();runJourneySearch('enter');}});document.querySelectorAll('.reactivate-journey').forEach(button=>button.addEventListener('click',reactivateSearchRecord));document.querySelectorAll('.open-search-result').forEach(button=>button.addEventListener('click',openSearchRecord));}
function runJourneySearch(source){filterJourneySearch();const query=(journeySearchInput?.value||'').trim();const visibleResults=journeySearchResults?[...journeySearchResults.querySelectorAll('.search-result-card')].filter(card=>!card.hidden).length:0;usageEvent('search_run',{module:'journey_search',action:'search',source,query_length:query.length,result_count:visibleResults});}
function filterJourneySearch(){if(!journeySearchResults)return;const query=(journeySearchInput?.value||'').trim().toLowerCase();let shown=0;journeySearchResults.querySelectorAll('.search-result-card').forEach(card=>{const match=!query||card.dataset.search.includes(query);card.hidden=!match;if(match)shown++;});let empty=journeySearchResults.querySelector('.search-empty');if(!shown){if(!empty){empty=document.createElement('div');empty.className='search-empty';empty.textContent='No matching journeys found.';journeySearchResults.appendChild(empty);}empty.hidden=false;}else if(empty)empty.hidden=true;}
function reactivateSearchRecord(event){const card=event.currentTarget.closest('.search-result-card');if(!card)return;card.classList.remove('dormant');card.querySelector('.record-state').className='record-state active-state';card.querySelector('.record-state').textContent='Active · Inquiry';event.currentTarget.remove();}
function openSearchRecord(event){const result=event.currentTarget.closest('.search-result-card');const name=result?.querySelector('strong')?.textContent.trim();if(!name)return;const boardCard=[...document.querySelectorAll('.journey-card')].find(card=>card.querySelector('.card-top strong')?.textContent.trim()===name);if(boardCard){closeDashboardModals();boardCard.click();return;}const state=result.querySelector('.record-state')?.textContent||'Record';result.querySelector('p').textContent=`${state}. This search result is not on the active board.`;}
function usageEvent(type,details={}){if(typeof window.trackUsageEvent==='function')window.trackUsageEvent(type,details);}
function syncUsageFranchiseSelection(source,changedFranchiseId=null,checked=null){const ids=[...selectedFranchiseIds].map(Number).sort((a,b)=>a-b);if(typeof window.updateUsageSessionContext==='function')window.updateUsageSessionContext({selected_franchise_ids:ids});usageEvent('franchise_filter_changed',{module:'franchise_filter',action:'change',source,selected_franchise_ids:ids,selected_count:ids.length,changed_franchise_id:changedFranchiseId,checked});}
function titleCase(value){return String(value||'').replace(/_/g,' ').replace(/\b\w/g,char=>char.toUpperCase());}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
logoutButton.addEventListener('click',logout);
function logout(){localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(USER_KEY);window.location.replace('index.html');}
const journeyStyle=document.createElement('link');journeyStyle.rel='stylesheet';journeyStyle.href='journey_panel.css';document.head.appendChild(journeyStyle);
const journeyScript=document.createElement('script');journeyScript.src='journey_panel.js';document.body.appendChild(journeyScript);
const inquiryStyle=document.createElement('link');inquiryStyle.rel='stylesheet';inquiryStyle.href='inquiry_modal.css';document.head.appendChild(inquiryStyle);
const inquiryScript=document.createElement('script');inquiryScript.src='inquiry_modal.js';document.body.appendChild(inquiryScript);