function initInquiryModal(){
  const API='https://x58r-xped-p4y6.n7e.xano.io/api:0Ddhs4dT';
  const token=localStorage.getItem('ads_journey_token');
  const FILTER_KEY='ads_journey_franchise_filter';
  const trigger=document.getElementById('newInquiryButton');
  if(!trigger)return;
  const host=document.createElement('div');
  host.innerHTML=`<div id="inquiryModalBackdrop" class="inquiry-modal-backdrop" hidden></div><section id="inquiryModal" class="inquiry-modal" hidden aria-modal="true" role="dialog"><div class="inquiry-modal-head"><div><p class="section-kicker">Messenger Intake</p><h2>New Inquiry</h2></div><button id="closeInquiryModal" class="secondary-button" type="button">← Back</button></div><form id="dashboardInquiryForm" class="inquiry-modal-form"><div class="inquiry-modal-grid"><label><span>Facebook name *</span><input id="modalFacebookName" type="text" required></label><label><span>Branch / location *</span><select id="modalFranchiseId" required><option value="">Loading branches...</option></select></label><label class="full"><span>Facebook profile URL *</span><input id="modalFacebookProfileUrl" type="url" placeholder="https://facebook.com/username" required></label><label><span>Facebook username</span><input id="modalFacebookUsername" type="text" placeholder="username"></label><label><span>Ad ID</span><input id="modalAdId" type="text"></label><label><span>First message time *</span><input id="modalFirstMessageAt" type="datetime-local" required></label><label><span>Initial inquiry</span><select id="modalInquiryType"><option value="">Select if known</option><option value="rates">Rates</option><option value="schedule">Schedule</option><option value="free_trial">Free Trial</option><option value="visit">Visit</option><option value="enrollment">Enrollment</option><option value="other">Other</option></select></label><label class="full"><span>Initial note</span><textarea id="modalInitialNote" rows="3" placeholder="What did the parent ask about?"></textarea></label></div><div id="inquiryModalError" class="inquiry-modal-error" hidden><span id="inquiryModalErrorText"></span><button id="openExistingJourneyButton" class="secondary-button inquiry-existing-button" type="button" hidden>Open Existing Journey</button></div><div class="inquiry-modal-actions"><button id="clearInquiryModal" class="secondary-button" type="button">Clear</button><button id="saveInquiryModal" class="journey-primary" type="submit">Create Inquiry</button></div></form></section>`;
  document.body.appendChild(host);
  const modal=document.getElementById('inquiryModal'),backdrop=document.getElementById('inquiryModalBackdrop'),form=document.getElementById('dashboardInquiryForm'),franchise=document.getElementById('modalFranchiseId'),errorBox=document.getElementById('inquiryModalError'),errorText=document.getElementById('inquiryModalErrorText'),existingButton=document.getElementById('openExistingJourneyButton'),saveButton=document.getElementById('saveInquiryModal');
  trigger.addEventListener('click',openModal);document.getElementById('closeInquiryModal').addEventListener('click',closeModal);backdrop.addEventListener('click',closeModal);document.getElementById('clearInquiryModal').addEventListener('click',resetForm);existingButton.addEventListener('click',()=>{const query=existingButton.dataset.query||'';if(!query)return;closeModal();window.dispatchEvent(new CustomEvent('open-existing-journey',{detail:{query}}));});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeModal();});
  form.addEventListener('submit',createInquiry);
  async function openModal(){resetForm();modal.hidden=false;backdrop.hidden=false;document.body.classList.add('modal-open');await loadFranchises();document.getElementById('modalFacebookName').focus();}
  function closeModal(){modal.hidden=true;backdrop.hidden=true;document.body.classList.remove('modal-open');}
  function resetForm(){form.reset();errorBox.hidden=true;errorText.textContent='';existingButton.hidden=true;existingButton.dataset.query='';setDefaultTime();}
  function setDefaultTime(){const now=new Date();const local=new Date(now.getTime()-now.getTimezoneOffset()*60000);document.getElementById('modalFirstMessageAt').value=local.toISOString().slice(0,16);}
  async function loadFranchises(){franchise.disabled=true;franchise.innerHTML='<option value="">Loading branches...</option>';try{const response=await fetch(`${API}/ad_franchises`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('Unable to load franchise locations.');const data=await response.json();const rows=Array.isArray(data)?data:(data.items||data.records||data.franchise||data.franchises||[]);const saved=JSON.parse(localStorage.getItem(FILTER_KEY)||'null');const selectedIds=Array.isArray(saved)&&saved.length?new Set(saved.map(Number)):null;const available=selectedIds?rows.filter(row=>selectedIds.has(Number(row.id))):rows;franchise.innerHTML='<option value="">Select branch</option>';available.forEach(row=>{const option=document.createElement('option');option.value=row.id;option.textContent=row.location||row.name||row.franchise_name||row.branch_name||`Branch ${row.id}`;franchise.appendChild(option);});if(!available.length){franchise.innerHTML='<option value="">No selected locations</option>';franchise.disabled=true;return;}franchise.disabled=false;}catch(error){franchise.innerHTML='<option value="">Unable to load branches</option>';showError(error.message);}}
  async function createInquiry(event){event.preventDefault();if(!form.reportValidity())return;const profile=document.getElementById('modalFacebookProfileUrl').value.trim();const normalizedProfile=/^https?:\/\//i.test(profile)?profile:`https://${profile}`;const payload={facebook_name:document.getElementById('modalFacebookName').value.trim(),facebook_profile_url:normalizedProfile,facebook_username:document.getElementById('modalFacebookUsername').value.trim()||null,franchise_id:Number(franchise.value),ad_id:document.getElementById('modalAdId').value.trim()||null,first_message_at:new Date(document.getElementById('modalFirstMessageAt').value).getTime(),inquiry_type:document.getElementById('modalInquiryType').value||null,initial_note:document.getElementById('modalInitialNote').value.trim()||null,status:'new',is_active:true,parent_id:null,student_id:null};saveButton.disabled=true;saveButton.textContent='Creating...';errorBox.hidden=true;existingButton.hidden=true;try{const response=await fetch(`${API}/ad_inquiry_create`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||data.error||data.detail||'Unable to create inquiry.');closeModal();window.dispatchEvent(new CustomEvent('inquiry-created',{detail:data}));}catch(error){const message=String(error.message||'Unable to create inquiry.');const duplicate=/already has an inquiry record|already exists/i.test(message);showError(message,duplicate?normalizedProfile:'');}finally{saveButton.disabled=false;saveButton.textContent='Create Inquiry';}}
  function showError(message,existingQuery=''){errorText.textContent=message;existingButton.hidden=!existingQuery;existingButton.dataset.query=existingQuery||'';errorBox.hidden=false;}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initInquiryModal);else initInquiryModal();