(function(){
const API='https://x58r-xped-p4y6.n7e.xano.io/api:0Ddhs4dT';
const token=localStorage.getItem('ads_journey_token');
let currentJourneyId=0,currentFranchiseId=0;
function init(){const card=document.getElementById('scheduleActionCard');const form=document.getElementById('scheduleForm');if(!card||!form)return false;if(document.getElementById('stage1NotInterestedAction'))return true;const action=document.createElement('div');action.id='stage1NotInterestedAction';action.className='handoff-actions';action.innerHTML='<button id="stage1NotInterestedButton" class="secondary-button" type="button">No Longer Interested</button>';const closeForm=document.createElement('form');closeForm.id='stage1NotInterestedForm';closeForm.className='schedule-form';closeForm.hidden=true;closeForm.style.display='none';closeForm.innerHTML='<label class="schedule-note"><span>Note</span><textarea id="stage1NotInterestedNote" rows="2" placeholder="Why is the parent no longer interested?" required></textarea></label><div class="handoff-actions"><button id="stage1BackNotInterested" class="secondary-button" type="button">Back</button><button class="journey-primary" type="submit">Confirm No Longer Interested</button></div>';
card.append(action,closeForm);
document.getElementById('stage1NotInterestedButton').addEventListener('click',()=>{form.hidden=true;form.style.display='none';action.hidden=true;closeForm.hidden=false;closeForm.style.display='';closeForm.scrollIntoView({behavior:'smooth',block:'nearest'});});
document.getElementById('stage1BackNotInterested').addEventListener('click',()=>{closeForm.hidden=true;closeForm.style.display='none';document.getElementById('stage1NotInterestedNote').value='';action.hidden=false;form.hidden=false;form.style.display='';});
closeForm.addEventListener('submit',submitNotInterested);return true;}
async function submitNotInterested(event){event.preventDefault();if(!currentJourneyId)return;const note=document.getElementById('stage1NotInterestedNote').value.trim();if(!note)return;const button=event.currentTarget.querySelector('button[type="submit"]');button.disabled=true;button.textContent='Closing...';try{const response=await fetch(`${API}/ad_journey_not_interested`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({journey_id:currentJourneyId,note})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||data.error||data.detail||'Unable to close journey.');if(typeof window.trackUsageEvent==='function')window.trackUsageEvent('parent_not_interested',{module:'journey_panel',action:'close',target:'journey',journey_id:currentJourneyId,franchise_id:currentFranchiseId,stage:'inquiry'});if(typeof window.loadBoard==='function')await window.loadBoard();document.getElementById('closeJourneyPanel')?.click();}catch(error){alert(error.message);}finally{button.disabled=false;button.textContent='Confirm No Longer Interested';}}
function resetStage1Controls(){if(!init())return;const schedule=document.getElementById('scheduleForm');const action=document.getElementById('stage1NotInterestedAction');const closeForm=document.getElementById('stage1NotInterestedForm');if(schedule){schedule.hidden=false;schedule.style.display='';}if(action)action.hidden=false;if(closeForm){closeForm.hidden=true;closeForm.style.display='none';}const note=document.getElementById('stage1NotInterestedNote');if(note)note.value='';}
document.addEventListener('click',event=>{const row=event.target.closest('.journey-card');if(!row)return;const stage=row.closest('.journey-column')?.dataset.stage||'';if(stage!=='inquiry')return;currentJourneyId=Number(row.dataset.journeyId)||0;currentFranchiseId=Number(row.dataset.franchiseId)||0;setTimeout(resetStage1Controls,0);},true);
if(!init()){const observer=new MutationObserver(()=>{if(init())observer.disconnect();});observer.observe(document.documentElement,{childList:true,subtree:true});}
})();
